In [19]:
#matrix Operation
import numpy as np
print("Matrix Operation")
a=np.array([[2,4],[6,3]])
b=np.array([[1,2],[3,5]])
c=a+b
d=a-b
e=a*b
f=np.dot(a,b)
a_transpose=a.T
print("\nMatrix A:\n",a)
print("\nMatrix B:\n",b)
print("\nAddition:\n",c)
print("\nSubstraction:\n",d)
print("\nMultiplication (Element-wise):\n",e)
print("\nMultiplication (Row x Column):\n",f)
print("\nTranspose:\n",a_transpose)

Matrix Operation

Matrix A:
 [[2 4]
 [6 3]]

Matrix B:
 [[1 2]
 [3 5]]

Addition:
 [[3 6]
 [9 8]]

Substraction:
 [[ 1  2]
 [ 3 -2]]

Multiplication (Element-wise):
 [[ 2  8]
 [18 15]]

Multiplication (Row x Column):
 [[14 24]
 [15 27]]

Transpose:
 [[2 6]
 [4 3]]


In [8]:
#with SVD
import numpy as np
#create a sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])

#perform SVD
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix(with reduced dimensions):")
print(X_reconstructed)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
